e2e: Fix test having bad URL
The previous approach spin up a mock test server but use the URL from
	fmt.Sprintf("http://%s/", l.Addr().String())
which led to a malformed URL and failed test with

	```
    fetch_test.go:57: cannot execute a git command
        Error: exit status 128
        Args: []string{"/usr/local/bin/git", "-c", "http.extraHeader=Authorization: Bearer valid-server-auth-token", "push", "-f", "http://[::]:42989/", "master:master"}
        Output: fatal: unable to access 'http://[::]:42989/': URL using bad/illegal format or missing URL
	```

Switch to use the server provided by 'httptest' package to simplify the
code and fix the test.